jobs:
  test:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Start
        uses: actions/checkout@v2
      - name: Install Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Checks
        run: ./ci/run

name: Build

on:
  schedule:
    - cron: "0 */3 * * *"
